### ISSUE TITLE
Need to add a space before ";" (semi-colon)?

### ISSUE THREAD

**Issue by lbrachet** [octodns/octodns-route53#55]
Hello,

I'm trying to add a DMARC TXT and I always have "**unescaped ;**".

#### Input:
```
_dmarc:
  - type: TXT
    value: 'v=DMARC1; p=quarantine'
```

#### Result:
`unescaped ; in "v=DMARC1; p=quarantine"`

#### Input:
```
_dmarc:
  - type: TXT
    value: "v=DMARC1; p=quarantine"
```

#### Result:
`unescaped ; in "v=DMARC1; p=quarantine"`

#### Input:
```
_dmarc:
  - type: TXT
    value: "v=DMARC1\; p=quarantine"
```

#### Result:
`yaml.scanner.ScannerError: while scanning a double-quoted scalar
found unknown escape character ';'`

#### Input:
```
_dmarc:
  - type: TXT
    value: v=DMARC1; p=quarantine
```

#### Result:
`unescaped ; in "v=DMARC1; p=quarantine"`

### TEST 5

So I tried with an escaping "\" before the ";":

#### Input:
```
_dmarc:
  - type: TXT
    value: v=DMARC1\; p=quarantine
```

#### Result:
`['v=DMARC1\; p=quarantine']> (config)`

### TEST 6

But there is the "\" which is not great. ;)

#### Input:
```
_dmarc:
  - type: TXT
    value: v=DMARC1\; p=quarantine
```

#### Result:
`['v=DMARC1\; p=quarantine']> (config)`

What am I doing wrong?

Thanks.

**Comment by ross** [comment]
```yaml
_dmarc:
  - type: TXT
    value: v=DMARC1\; p=quarantine
```

^ is the correct/simplest way to denote a record with an escaped `;` in it.  After pushing that up to Route53 I can query the result and get the desired/expected value back:

```console
(env) coho:octodns-route53 ross$ dig +short TXT _dmarc.exxampled.com. @ns-2027.awsdns-61.co.uk.
"v=DMARC1; p=quarantine"
```

If you for some reason want to quote the string in YAML you'll need to use `\\` so that YAML parsing will put a single `\` in the resulting value. `\` is the YAML string escape character so it takes two of them to get a single literal `\`.

```yaml
_dmarc:
  - type: TXT
    value: "v=DMARC1\\; p=quarantine"
```

**Comment by lbrachet** [comment]
Thanks Ross, it's good for me!
